@startuml
业务系统 -> 同舟后端:增加待办类型对应的元数据配置
业务系统 -> 同舟后端: 创建待办任务(param:待办类型+业务摘要)
同舟后端->业务系统:创建待办完成
同舟后端<-同舟前端:查询:待办任务
同舟后端 --> 同舟后端: 查询:待办任务
同舟后端 --> 同舟后端:查询:待办配置化信息
同舟后端-->同舟后端:返回:待办任务
同舟前端<-同舟后端:返回:待办任务
同舟前端->同舟前端:根据待办配置的渲染规则渲染待办
同舟前端->同舟后端:操作待办（完成、取消）
同舟后端-->业务系统:执行业务
业务系统-->同舟后端:操作待办（完成、取消）
同舟前端<-业务系统:操作待办（完成、取消）
@enduml