@startuml
业务系统 -> 诺亚:增加待办类型对应的元数据配置
业务系统 -> 诺亚: 创建待办任务(param:待办类型+业务摘要)
诺亚->业务系统:创建待办完成

同舟后端<-同舟前端:查询:待办任务
同舟后端 --> 诺亚: 查询:待办任务
诺亚 --> 诺亚:查询:待办配置化信息
诺亚-->同舟后端:返回:待办任务
同舟前端<-同舟后端:返回:待办任务
同舟前端->同舟前端:根据待办配置的渲染规则渲染待办
业务系统 -> 诺亚:刷新待办(param:待办Id+业务摘要)
业务系统 <- 诺亚:刷新待办成功
同舟前端->同舟后端:操作待办（完成、取消）
同舟后端-->业务系统:执行业务
业务系统-->诺亚:操作待办（完成、取消）
同舟前端<-业务系统:操作待办（完成、取消）
@enduml