server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.70.151.153:3306/myStudyDB?characterEncoding=utf-8&useSSL=false
    username: root
    password: 19950808
  aop:
    proxy-target-class=false
#activeMq 相关配置
  activemq:
    broker-url: nio://124.70.151.153:61608  #mq 服务器地址    tcp://124.70.151.153:61616       nio://124.70.151.153:61618  (nio+auto)  nio://124.70.151.153:61608  tcp://124.70.151.153:61608
    user: admin
    password: admin
  # false : queue    true:topic
  jms:
    pub-sub-domain: true
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.my_springboot.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true


#自定定义队列名称
myqueue: boot-activemq-queue
myTopic: boot-activemq-topic



