server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.70.151.153:3306/myStudyDB?characterEncoding=utf-8&useSSL=false
    username: root
    password: 19950808
  aop:
    proxy-target-class=false
  #activeMq 相关配置
  activemq:
    broker-url: nio://124.70.151.153:61608  #mq 服务器地址    tcp://124.70.151.153:61616       nio://124.70.151.153:61618  (nio+auto)  nio://124.70.151.153:61608  tcp://124.70.151.153:61608
    user: admin
    password: admin
  # false : queue    true:topic
  jms:
    pub-sub-domain: true

  redis:
    host: 121.5.224.189
    port: 6379
    password: 19950808
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

  #数据源配置
  data:
    mongodb:
      # 主机地址
      host: 121.5.224.189
      # 数据库
      database: test
      # 默认端口是27017
      port: 27017
      #也可以使用uri连接
      #uri: mongodb://bobo:123456@180.76.159.126:27017,180.76.159.126:27018,180.76.159.126:27019/articledb?connect=replicaSet&slaveOk=true&replicaSet=myrs
#      username: chenmin
#      password: 123456
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.my_springboot.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true


#自定定义队列名称
myqueue: boot-activemq-queue
myTopic: boot-activemq-topic




sql: select * from sss where A= #{} and b = #{};



